Fix Type 'ChartDataSet' does not conform to protocol 'RangeReplaceabl…
danielgindi/Charts pull request #4881
Opened 2022-08-14 07:34 UTC by kanstantsin-bucha

For some reason I got this error on xCode - beta.

Fix implemented by:
* implementing method of RangeReplaceableCollection protocol for ChartDataSet 
* renaming of Range(objc ChartsRange) class cause it Shadows swift Range class that leads to compile errors.

2022-08-23 10:55 UTC, josipbernat commented
Can somebody merge this PR? iOS 16 is near and this error breaks my app. Thanks!

2022-08-24 07:44 UTC, emadhegab commented
@danielgindi  I think this one is top priority if you don't mind

2022-08-25 14:29 UTC, richardsimkins commented
This issue is also happening on 3.6.0 with Xcode 14 beta 6. Will merging this fix also fix it for people not on version 4.x.x?

2022-08-28 00:16 UTC, pmairoldi requested changes
The change works but I'd rather not change the `Range` class's name.

2022-08-28 00:16 UTC, pmairoldi commented on Source/Charts/Data/Implementations/Standard/ChartDataSet.swift
> +        _ subrange: Range<Index>,
I think if we just use `Swift.Range<Index>` here we don't have to rename the other Range class. I think it would be a better fix for the problem.

2022-08-28 00:24 UTC, pmairoldi commented
Close in favour of https://github.com/danielgindi/Charts/pull/486. Thanks for the contribution.

2022-08-28 00:24 UTC, closed without merging

2022-08-28 18:43 UTC, zygoat commented
#486 is seven years old and unrelated. I presume that superseding issue number is a typo?

2022-08-28 18:47 UTC, pmairoldi commented
Ahhhh sorry about that it was https://github.com/danielgindi/Charts/issues/4861